### ISSUE TITLE
Did you consider implementing the package as a fable extension?

### ISSUE THREAD

**Issue by brunocarlin** [asael697/bayesforecast#6]
Recently fable and the tsibble package have greatly simplified modeling with time series, have you considered moving the interface to comply with their standards?

**Comment by asael697** [comment]
As you might know, fable is just an interface of forecast package using tsibble, sadly I am not in that phase yet. But you can check the bayesmodels package: 
 https://github.com/AlbertoAlmuinha/bayesmodels

Right now am working on extending the number of models for a full library but using the basic R ts class that works for simple time series.  If you need some further help please contact me.
